//! Build script. Besides the usual Tauri codegen it generates the app's ACL
//! manifest, which is what actually keeps the Web pane's browser tabs away from
//! Chronicle's commands.
//!
//! Without an app manifest Tauri treats *local* origins (and a custom scheme
//! like `chronicle-file://` is a local origin on macOS) as exempt from the ACL,
//! so any page loaded in a child webview could invoke every `#[tauri::command]`
//! in the binary. Generating a manifest turns the ACL on for app commands; the
//! `default` permission it defines is then granted, in `capabilities/default.json`,
//! to the `main` webview and to nothing else.
//!
//! The command list is read straight out of `tauri::generate_handler![…]` in
//! `src/main.rs`, so a command added later cannot be forgotten here.

use std::path::PathBuf;
use std::{env, fs};

/// Pull the command identifiers out of `tauri::generate_handler![ … ]`,
/// keeping only the last path segment (`power::get_power_source` → `get_power_source`).
fn command_names(src: &str) -> Vec<String> {
    let re = regex::Regex::new(r"(?s)generate_handler!\[(.*?)\]").expect("handler regex");
    let body = re
        .captures(src)
        .map(|c| c[1].to_string())
        .expect("no tauri::generate_handler![…] in src/main.rs");
    let mut names: Vec<String> = body
        .split(|c: char| c == ',' || c.is_whitespace())
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(|s| s.rsplit("::").next().unwrap_or(s).to_string())
        .collect();
    names.sort();
    names.dedup();
    names
}

/// glob metacharacters in a literal path (the same escaping `glob::Pattern::escape` does).
fn glob_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '?' | '*' | '[' | ']' => { out.push('['); out.push(c); out.push(']'); }
            _ => out.push(c),
        }
    }
    out
}

fn main() {
    println!("cargo:rerun-if-changed=src/main.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let src = fs::read_to_string("src/main.rs").expect("unable to read src/main.rs");
    let commands = command_names(&src);
    assert!(!commands.is_empty(), "generate_handler![] listed no commands");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    // the test in web.rs reads this back with include_str!, so it checks exactly
    // the list this script fed to the manifest
    fs::write(out_dir.join("commands.txt"), commands.join("\n")).expect("write commands.txt");

    // One permission per command plus a `default` set holding all of them. The
    // file lives in OUT_DIR rather than `permissions/` so nothing generated ever
    // lands in the source tree.
    let perms_dir = out_dir.join("app-permissions");
    fs::create_dir_all(&perms_dir).expect("create app-permissions");
    let allow_ids: Vec<String> = commands.iter().map(|c| format!("allow-{}", c.replace('_', "-"))).collect();
    let mut toml = String::from("# Automatically generated by build.rs - DO NOT EDIT!\n\n[default]\ndescription = \"Every command Chronicle's own UI invokes.\"\npermissions = [\n");
    for id in &allow_ids { toml.push_str(&format!("  \"{id}\",\n")); }
    toml.push_str("]\n");
    for (cmd, id) in commands.iter().zip(&allow_ids) {
        toml.push_str(&format!(
            "\n[[permission]]\nidentifier = \"{id}\"\ndescription = \"Enables the {cmd} command.\"\ncommands.allow = [\"{cmd}\"]\n"
        ));
    }
    fs::write(perms_dir.join("app.toml"), toml).expect("write app.toml");

    let pattern: &'static str = Box::leak(
        format!("{}/*", glob_escape(&perms_dir.to_string_lossy())).into_boxed_str(),
    );

    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().permissions_path_pattern(pattern)),
    )
    .expect("tauri build");
}
